### ISSUE TITLE
If I make some changes on OS security option, I cannot use anymore my stored private key

### ISSUE THREAD

**Issue by MarcoLude** [uport-project/react-native-uport-signer#24]
Hi all,

I'd like to understand how the library is supposed to work when a user changes his OS settings. On a Samsung S10 I've tried to create a seed via uportSignerHD.createSeed with the level set to "prompt", and then I've used uportSignerHD.showSeed to show the seedPhrase. So far so good, it worked and it requested the fingerprint before showing the 12 words.
But when in OS setting I've added a second fingerprint, the uportSignerHD.showSeed method stopped working, signaling this error:

"Error: Key permanently invalidated"

Can you please explain to me how the app behaves with such kind of operations (pin changes, faceId added/removed, fingerprint added/removed, etc..) and how you suggest to handle them?

Thank you very much

**Comment by mirceanis** [comment]
@MarcoLude
This behavior is a feature of the underlying AndroidKeyStore/fingerprint mechanism.
Essentially they consider that when you add a new fingerprint it is necessary to invalidate all previously stored key material.
More information about the theoretical expected behavior is here: https://developer.android.com/reference/android/security/keystore/KeyPermanentlyInvalidatedException
Note the phrase:
> Additionally, keys configured to require user authentication to take place for every of the keys, are also permanently invalidated once a new fingerprint is enrolled or once no more fingerprints are enrolled.

Unfortunately this behavior is not consistent across devices because of implementation differences in different android versions, but you can catch the error and handle it if it appears.

The best way to handle this scenario is to let the user know that "The security settings on the device have changed" and that the app needs to reset.
At this point they should be given the option to type their previously saved 12 word seed phrase (or ignore and start from scratch)

This behavior is only for keys/seeds that have been created or imported with `prompt` or `single_prompt` protection level. Those using `simple` are not affected.

I hope this helps.

**Comment by MarcoLude** [comment]
@mirceanis 
Thank you for your answer, now I understand better this feature.
Thank you also for your suggestion!
