### ISSUE TITLE
UPORT_ROOT_DERIVATION_PATH is unknown

### ISSUE THREAD

**Issue by rizwanzaheer** [uport-project/react-native-uport-signer#29]
I'm trying to create verifiable claims using this library but **UPORT_ROOT_DERIVATION_PATH** is unknown for, I don't know how to figure-out this 
`RNUportHDSigner.signJwt(
        seedAlias,
        RNUportHDSigner.UPORT_ROOT_DERIVATION_PATH,
        base64EncodedJwt,
        myClaim
  ).then((jwtSig: any) => {
        console.warn("jwtSig is: ", jwtSig);
  });`

**Comment by mirceanis** [comment]
Are you getting an error when you run this code?

`UPORT_ROOT_DERIVATION_PATH` is a constant exported by the `RNUportHDSigner` module.
Its value is `m/7696500'/0'/0'/0'`

The `derivationPath` parameter is the one that dictates which privateKey is derived from the seed that corresponds to that `seedAlias`, according to [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) & [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki)
That private key is the one that will sign the JWT of the verifiable credential.

You can also use your own path for that parameter (for example `m/44'/60'/0'/0/0`, used by most ETH wallet apps)

There is a section in the readme detailing this:
https://github.com/uport-project/react-native-uport-signer#key-derivation-paths

It would be very helpful if you pointed out which part does not make sense, so that we can improve.
You're also welcome to open a PR with a better description.

**Comment by mirceanis** [comment]
Closing this as it seems to not be an issue.
Please re-open or file a new issue if needed.
